Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", ip: "192.168.5.126"
  config.vm.synced_folder "./certs", "/certs"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: <<-SHELL

    # Inclui certificado
    sudo cat /certs/id_curso.pub >> .ssh/authorized_keys

    # atualizada sistema
    sudo apt update

    # instala nginx
    sudo apt install nginx -y
  SHELL
end
